language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Support library
    - extra-android-support
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-28

before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew

script:
  - ./gradlew build -Pbuild=devCI
  - ./gradlew jacocoTestReport coveralls -Pbuild=devCI

after_success:
  - echo "Build Passed - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"